spring.application.name=GeminiNutrition
GEMINI_API_KEY=AIzaSyAF67C3erWXFBhdmqD3Q13sizH-30_vJr0
frontend.url=http://localhost:5173,http://localhost:3000
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent