spring.application.name=GeminiNutrition
GEMINI_API_KEY=${env.GEMINI_API_KEY}
frontend.url=http://localhost:5173,http://localhost:3000
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent



